// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Ln62ZaM88LEjGCMfBkRoKcAJRWyAAZ8',
    appId: '1:962083532493:web:8de0e5d3820e814d508384',
    messagingSenderId: '962083532493',
    projectId: 'messinter-16708',
    authDomain: 'messinter-16708.firebaseapp.com',
    storageBucket: 'messinter-16708.appspot.com',
    measurementId: 'G-NHQ36LTHP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmUoWyTKnYGtEr5-QBsBKu2kFTwAPtqf4',
    appId: '1:962083532493:android:bdfb66759ea755b5508384',
    messagingSenderId: '962083532493',
    projectId: 'messinter-16708',
    storageBucket: 'messinter-16708.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeyqeFCY6DnwaF955utk8VAJPsMuqBF0M',
    appId: '1:962083532493:ios:6735a0c046bc197e508384',
    messagingSenderId: '962083532493',
    projectId: 'messinter-16708',
    storageBucket: 'messinter-16708.appspot.com',
    iosClientId: '962083532493-3at26ei3d11k7p389oa0hvpkddcql5qk.apps.googleusercontent.com',
    iosBundleId: 'com.example.messinterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeyqeFCY6DnwaF955utk8VAJPsMuqBF0M',
    appId: '1:962083532493:ios:40560ab247896924508384',
    messagingSenderId: '962083532493',
    projectId: 'messinter-16708',
    storageBucket: 'messinter-16708.appspot.com',
    iosClientId: '962083532493-88v0vi19rrhd9ojero92d8em6iq9kjiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.messinterApp.RunnerTests',
  );
}
